name: CI Integration + UI + Dependency Check

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Node.js for Selenium test
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Selenium WebDriver
      run: npm install selenium-webdriver

    - name: Build PHP web app Docker image
      run: docker build -f web.Dockerfile -t my-php-app .

    - name: Run PHP web app container
      run: docker run -d --name web -p 8080:80 my-php-app

    - name: Wait for web app to be ready
      run: |
        for i in {1..10}; do
          if curl -sSf http://localhost:8080/index.html > /dev/null; then
            echo "✅ Web is up"
            break
          fi
          echo "⏳ Waiting for web to start..."
          sleep 3
        done

    - name: Run Selenium UI Test
      run: node tests/UITest.mjs

    - name: Run OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: "MyWebApp"
        path: "."
        format: "HTML"
        out: "dependency-check-report"

    - name: Upload dependency report
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-report
        path: dependency-check-report

    - name: Commit workflow to local Git server
      run: |
        git config --global user.name "Lim-Tze-Kit"
        git config --global user.email "2301861@sit.singaporetech.edu.sg"
        git remote add local http://localhost:3000/repository.git || true
        git fetch local || true
        git add .github/workflows/action-test.yml
        git commit -m "Add CI workflow" || echo "Nothing to commit"
        git push local HEAD:main
