name: CI Integration + UI + Dependency Check

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Create test network
      run: docker network create testnet

    - name: Build web app container
      run: docker build -f web.Dockerfile -t my-php-app .

    - name: Start web app on custom network
      run: |
        docker run -d --rm --name webapp \
          --network testnet \
          -p 8080:80 \
          my-php-app

    - name: Wait for web app to start
      run: |
        for i in {1..10}; do
          if docker exec webapp curl -s http://localhost/index.html > /dev/null; then
            echo "Web is up"
            break
          fi
          echo "Waiting for web to start..."
          sleep 3
        done

    - name: Run Selenium UI test in container
      run: |
        docker run --rm \
          --network testnet \
          -v ${{ github.workspace }}/tests:/tests \
          selenium/standalone-chrome:latest-node \
          bash -c "cd /tests && npm install selenium-webdriver && node UITest.mjs"


    - name: Run OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: "MyWebApp"
        path: "."
        format: "HTML"
        out: "dependency-check-report"

    - name: Upload dependency report
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-report
        path: dependency-check-report

    - name: Commit workflow to local Git server
      run: |
        git config --global user.name "Lim-Tze-Kit"
        git config --global user.email "2301861@sit.singaporetech.edu.sg"
        git remote add local http://localhost:3000/repository.git || true
        git fetch local || true
        git add .github/workflows/action-test.yml
        git commit -m "Add CI workflow" || echo "Nothing to commit"
        git add .github/workflows/action-test.yml
        git commit -m "Add CI workflow" || echo "Nothing to commit"
        git push local HEAD:main
